### ISSUE TITLE
Is it possible to run the rtsp server with a raw stream?

### ISSUE THREAD

**Issue by marekyggdrasil** [jackersson/gst-python-tutorials#4]
Hi all!

First of all @jackersson thank you for developing those examples, they are really excellent and if not you, I think there would be almost nothing to get started.

I am running your [RTSP server example](https://github.com/jackersson/gst-python-tutorials/blob/bb13aeccc987fb4753ab672d2d5430d42af466d8/launch_pipeline/run_rtsp.py) and I am able to see the preview using VLC on my local computer.

I would like to try a raw stream because for some reason H264 lags a lot, looks like there is some kind of noise, frames are lost etc (hard for me to explain, I'm really not an expert).

The pipeline with H264 encoding which works great

```
gst-launch-1.0 appsrc emit-signals=True is-live=True ! videoconvert n-threads=4 ! video/x-raw,format=I420 ! x264enc tune=zerolatency ! queue max-size-buffers=8 ! rtph264pay config-interval=1 name=pay0 pt=96
```

I can view the video using VLC media player and when I stop streaming by pressing stop on VLC it emits `GST_FLOW_FLUSHING` signal of type `gi.repository.Gst.FlowReturn`.

Now, my attempt to make it stream raw video consists of removing the `x264enc` encoder from the pipeline and replacing `rtph264pay` with `rtpvrawpay` which to my understanding should be its equivalent for raw encoding. The pipeline looks as follows.

```
gst-launch-1.0 appsrc emit-signals=True is-live=True ! videoconvert n-threads=4 ! video/x-raw,format=I420 ! queue max-size-buffers=8 ! rtpvrawpay name=pay0 pt=96
```

This one generates exactly three frames then triggers `retval != Gst.FlowReturn.OK`, no image appears on my VLC every three frames keeps emitting `GST_FLOW_FLUSHING` signal of type `gi.repository.Gst.FlowReturn`.

I have been trying to debug it and all I could find was `The function returns GST_FLOW_FLUSHING if the pad was flushing` in [here](https://gstreamer.freedesktop.org/documentation/gstreamer/gstpad.html?gi-language=c) which actually doesn't tell me much.

I was wondering if you could give me some hints how to make this raw stream work with RTSP server?

**Comment by jackersson** [comment]
Hi @marekyggdrasil, 

I took official [gst-rtsp-server](https://github.com/GStreamer/gst-rtsp-server). Built it with: 
```
git clone https://github.com/GStreamer/gst-rtsp-server.git
cd gst-rtsp-server
git checkout 1.14.5
./autogen.sh
make
sudo make install
```
Then run Rtsp stream:
```
./examples/test-launch "videotestsrc ! rtpvrawpay name=pay0 pt=96"
```
And via terminal I'm able to see the stream with:
```
gst-launch-1.0 rtspsrc location=rtsp://127.0.0.1:8554/test ! rtpvrawdepay ! videoconvert ! gtksink
```

But with VLC it shows me an error. 
```
Your input can't be opened:
VLC is unable to open the MRL 'rtsp://127.0.0.1:8554/test'. Check the log for details.
```

Now, with [run_rtsp](https://github.com/jackersson/gstreamer-python/blob/master/examples/run_rtsp.py). I modified it a little bit to make same experiment. And now I'm also able to get stream via terminal
```
gst-launch-1.0 rtspsrc location=rtsp://localhost:8554//stream.rtp ! rtpvrawdepay ! videoconvert n-threads=0 ! gtksink
```

But still not able to do it with VLC. How do you work with VLC?

**Comment by marekyggdrasil** [comment]
@jackersson could you share how you modified [run_rtsp](https://github.com/jackersson/gstreamer-python/blob/master/examples/run_rtsp.py) for the raw stream? I think it really might be the VLC issue, I would like to try with `gst-launch-1.0`.

I tried to build the one you linked but are you sure you linked the right repository? There is no `autogen.sh` in the one you linked.

> How do you work with VLC?

I just open `File > Open Network > Url` and put there `rtsp://localhost:8554//stream.rtp` and this works with H264 stream, although needs quite few frames before starts to render.

**Comment by jackersson** [comment]
Updated previous answer (autogen.sh). If you are using newer Gstreamer, than you can build it with meson (look [here](https://gist.github.com/jackersson/9d3b0c578c1e625b6b79ea04e2cebd15#gistcomment-3224133))

And for **run_rtsp.py** have a look at [commit](https://github.com/jackersson/gstreamer-python/commit/98424f8c21bd84805313d8890d789e739d115ffa). There is specified pipeline with **rtpvrawpay**.
```
python examples/run_rtsp.py
```
And in other terminal:
```
gst-launch-1.0 rtspsrc location=rtsp://localhost:8554//stream.rtp ! rtpvrawdepay ! videoconvert n-threads=0 ! gtksink
```
P.S. But to be honest it sometimes freezes frames. And it's noticeable. But maybe it is due to internet channel.

**Comment by marekyggdrasil** [comment]
@jackersson thanks for the example, it helped a lot, so I modified it a little bit and it works, here is the [gist](https://gist.github.com/marekyggdrasil/ede6961155ca6670dbc53eaac818dc6d)

1. Using `gst-launch-1.0` instead of VLC, I couldn't find anything useful in VLC logs
2. Lowering framerate to 10 per second seems to make it stop lag on my machine
3. Since it is a raw stream and not H264, picture looks sharp, no more digital noise

I think it is just too slow, I don't think its the internet channel, localhost should be fast enough to handle this resolution and frame rate even with raw stream, I will study the C examples you shared, I think it is more appropriate way of generating livestreams than Python with Numpy.
